"""
LaTeX Service

Handles compilation of LaTeX documents to PDF.
"""

import subprocess
import os
from pathlib import Path
from typing import Optional
from loguru import logger


class LaTeXService:
    """
    Service for compiling LaTeX documents to PDF.
    """
    
    def __init__(self, config: dict):
        """
        Initialize the LaTeX service.
        
        Args:
            config: LaTeX configuration dictionary
        """
        self.compiler = config.get("compiler", "pdflatex")
        self.compile_attempts = config.get("compile_attempts", 2)
        self.cleanup_aux = config.get("cleanup_aux_files", True)
        
        # Check if compiler is available
        self._compiler_available = self._check_compiler()
    
    def _check_compiler(self) -> bool:
        """Check if the LaTeX compiler is available."""
        try:
            result = subprocess.run(
                [self.compiler, "--version"],
                capture_output=True,
                text=True,
                timeout=10
            )
            if result.returncode == 0:
                logger.info(f"LaTeX compiler '{self.compiler}' is available")
                return True
        except FileNotFoundError:
            logger.error(f"LaTeX compiler '{self.compiler}' not found")
        except Exception as e:
            logger.error(f"Error checking LaTeX compiler: {e}")
        
        return False
    
    def compile(self, tex_file: Path) -> Optional[Path]:
        """
        Compile a LaTeX file to PDF.
        
        Args:
            tex_file: Path to the .tex file
            
        Returns:
            Path to the generated PDF, or None if compilation failed
        """
        if not self._compiler_available:
            logger.error("LaTeX compiler not available")
            return None
        
        tex_file = Path(tex_file)
        if not tex_file.exists():
            logger.error(f"TeX file not found: {tex_file}")
            return None
        
        output_dir = tex_file.parent
        pdf_file = output_dir / tex_file.with_suffix(".pdf").name
        
        # Compile (multiple passes for references)
        for attempt in range(self.compile_attempts):
            logger.debug(f"Compilation attempt {attempt + 1}/{self.compile_attempts}")
            
            try:
                result = subprocess.run(
                    [
                        self.compiler,
                        "-interaction=nonstopmode",
                        "-output-directory", str(output_dir),
                        str(tex_file)
                    ],
                    capture_output=True,
                    text=True,
                    timeout=60,
                    cwd=str(output_dir)
                )
                
                if result.returncode != 0:
                    logger.warning(f"Compilation warning/error (attempt {attempt + 1})")
                    logger.debug(f"LaTeX output: {result.stdout[-1000:]}")
                
            except subprocess.TimeoutExpired:
                logger.error("LaTeX compilation timed out")
                return None
            except Exception as e:
                logger.error(f"Compilation error: {e}")
                return None
        
        # Check if PDF was created
        if pdf_file.exists():
            logger.info(f"PDF created: {pdf_file}")
            
            # Cleanup auxiliary files
            if self.cleanup_aux:
                self._cleanup_aux_files(tex_file)
            
            return pdf_file
        else:
            logger.error(f"PDF not created: {pdf_file}")
            return None
    
    def _cleanup_aux_files(self, tex_file: Path):
        """Remove auxiliary files generated by LaTeX."""
        aux_extensions = [".aux", ".log", ".out", ".toc", ".lof", ".lot", ".fls", ".fdb_latexmk"]
        
        for ext in aux_extensions:
            aux_file = tex_file.with_suffix(ext)
            if aux_file.exists():
                try:
                    aux_file.unlink()
                    logger.debug(f"Removed {aux_file.name}")
                except Exception as e:
                    logger.debug(f"Could not remove {aux_file.name}: {e}")
    
    def is_available(self) -> bool:
        """Check if LaTeX compilation is available."""
        return self._compiler_available
